//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRF_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEAM
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public Nullable<int> ATTACK_LEVEL { get; set; }
        public Nullable<int> MIDFIELD_LEVEL { get; set; }
        public Nullable<int> DEFENSE_LEVEL { get; set; }
        public Nullable<int> GOALKEEPER_LEVEL { get; set; }
    }
}
